### ISSUE TITLE
Hugos Armory Error in Mistlands

### ISSUE THREAD

**Issue by FelipeCardona95** [Hugo-the-Dwarf/ValheimModsHTD#4]
Hi After mistlands update HugosArmorry Started spamming the console with an error, I have insolated the root cause and its Hugo, I enabled mod by mod, if you still dont trust me I can try just with the mod
![image](https://user-images.githubusercontent.com/11274437/206382391-3bee4ff5-653e-499e-8098-768dc5ea5649.png)
Log:https://pastebin.com/EvYFwZmn
![image](https://user-images.githubusercontent.com/11274437/206382620-0fe48770-e113-4284-98bb-b8f0113b2587.png)
![image](https://user-images.githubusercontent.com/11274437/206382711-04d24d82-72ae-4171-b6dd-bf8f99cbb19d.png)

let me know if you need more info

**Comment by Hugo-the-Dwarf** [comment]
As of 8.0.0 this issue should be resolved, as that code wasn't working so well just before mistlands, so it's been disabled. It'll be migrated to a new mod which will do it better.

**Comment by Hugo-the-Dwarf** [comment]
As checking your log it was the previous version you had loaded, which indeed would fail in Mistlands update, along with many other failures.

[Hugos Armory 7.1.5]
